name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install aqtinstall
      run: python3 -m pip install aqtinstall==1.2.5

    - name: Install Qt 5.15.13
      run: python3 -m aqt install 5.15.13 linux desktop -O ${{ github.workspace }}/Qt

    - name: Set up Qt environment
      run: |
        echo "$HOME/Qt/5.15.13/gcc_64/bin" >> $GITHUB_PATH
        echo "$HOME/Qt/5.15.13/gcc_64/lib" >> $GITHUB_PATH

    - name: Install build dependencies
      run: sudo apt-get install -y qt5-qmake qtbase5-dev qtdeclarative5-dev

    - name: Build project
      run: |
        mkdir build
        cd build
        qmake ../audio-to-text-convertor-app.pro
        make
